version: '3.8'

services:
  node:
    image: node:lts-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html/
    command:
      - sh
      - -c
      - |
        npm i
        npm run dev